spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

